print("Please enter the following information: ")
first_name = input("\nFirst name: ")
last_name = input("Last name: ")
email = input("Email address: ")
phone = input("Phone number: ")
job_title = input("Job title: ")
id_number = input("ID Number: ")
print("\nThe ID Card is: ")
print("----------------------------------------")
print(last_name.upper() + ', ' + first_name.title())
print(job_title.title())
print("ID: " + id_number)
print("\n" + email.lower())
print(phone)
print("----------------------------------------")